name:  MyGitHubAction-Basics
env:
  APPLICATION_NAME: "MyFlask"
  PACKAGE_NAME   : "flask-deploy-ver-${{ github.sha }}"

on: 
 push:
   branches: 
     - master
   
jobs:
  my_testing1:
     runs-on: ubuntu-latest
    
     steps:
       - name: Run a one-line script
         run: echo Hello, World!
       - name: Execute few commands
         run: |
             echo: "Execute commands1"
             echo: "Execute commands2"
             echo: "Application name: ${{ env.APPLICATION_NAME}}"
  my_deploy:
      runs-on: ubuntu-latest
      needs: [my_testing1]
      
      steps:
        - name: Run a one-line script
          run: echo Hello, World!       
        - name: Printing deployemnt package
          run: echo "Deploy package name is ${{ env.PACKAGE_NAME}}" 
          
     
