name:  MyGitHubAction-Basics
env:
  APPLICATION_NAME     : "MyFlask"
  DEPLOY_PACKAGE_NAME  : "flask-deploy-ver-${{ github.sha }}"

on: 
 push:
   branches: 
     - master
   
jobs:
  my_testing1:
     runs-on: ubuntu-latest
    
     steps:
       - name: Run a one-line script
         run: echo Hello, World!
       - name: Execute few commands
         run: |
           echo "Hello message1"
           echo "Hello message2"
           echo "Application name: ${{ env.APPLICATION_NAME }}"
       - name: List current Folder
         run: ls -la
       - name: Git clone my repo
         uses: actions/checkout@v1 
       - name: List current Folder
         run: ls -la     
       - name: Build and Push Docker Image
         uses: mr-smithers-excellent/docker-build-push@v4
         with:
            image: nanajanashia/demo-app
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }} 

          
          
     
